# Generated by Django 4.0.6 on 2022-08-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_followscount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowsCount',
            new_name='FollowersCount',
        ),
    ]
